name: Build and Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            output_path: build/windows/x64/runner/Release
            artifact_name: flutter_space_saver-windows
          - os: macos-latest
            output_path: build/macos/Build/Products/Release
            artifact_name: flutter_space_saver-macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Enable desktop
        run: |
          flutter config --enable-windows-desktop
          flutter config --enable-macos-desktop

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: flutter build windows --release

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: flutter build macos --release

      - name: Package Windows app
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Compress-Archive -Path "${{ matrix.output_path }}/*" -DestinationPath "${{ matrix.artifact_name }}.zip"

      - name: Package macOS app
        if: matrix.os == 'macos-latest'
        run: |
          cd "${{ matrix.output_path }}"
          zip -r "../../../../${{ matrix.artifact_name }}.zip" *.app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.zip
          retention-days: 5

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/flutter_space_saver-windows/flutter_space_saver-windows.zip
            artifacts/flutter_space_saver-macos/flutter_space_saver-macos.zip
          draft: false
          prerelease: false
          generate_release_notes: true

